version: 2.1
orbs:
  node: circleci/node@1.1.6
defaults: &defaults
  working_directory: ~/pomodoro.cc
  docker:
    - image: node:10
    - image: mongo:3.4

jobs:
  workspace:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
          - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v2-deps-{{ .Branch }}-
          - v2-deps-
      - run: npm install
      - run: cd app ; npm install
      - run: cd api ; npm install
      - persist_to_workspace:
          root: ~/
          paths:
            # - .cache
            - tasktimer.tk

  test_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: test_app
          command: |
            cd app
            npm t